people/damiri: Delaram graduation update.
uci-iasl/website pull request #32
Opened 2020-08-14 21:35 UTC by dcallega

2020-08-15 03:33 UTC, igorburago requested changes
After updating the `status` field, squash it back into a single commit
(removing the period at the end of the commit message and prepending
it with the `people/damiri:` prefix).

2020-08-15 03:33 UTC, iburago commented on content/people/damiri.md
>  status: Ph.D. Candidate
Please change the status to Ph.D. (removing the Candidate part).

2020-08-15 04:19 UTC, iburago commented
I skimmed through the other two pull requests, and would like to ask
you to adjust your commit message style slightly to match the one
generally established in the Git community. Specifically, please:

- *Do not end the commit subject line with a period*.
- *Formulate the commit subject line imperatively*, so that, prefaced
with “Apply this commit to”, it reads as a correct English sentence.

For more advice on commit message styling, I would recommend
taking a look at the ‘[How to Write a Git Commit Message][hgc]’ article
by Chris Beams. It is from 2014, but all of the recommendations
in it still stand.

[hgc]: https://chris.beams.io/posts/git-commit/

2020-08-15 04:51 UTC, iburago commented
Also, are the title of her dissertation and the month of her
defense known?

If so, it would be great to add a BibTeX entry for her
dissertation to the `static/bib/damiri.bib` and list it in the
publications on her page (similarly to the Master’s thesis).

(We can do that in a separate pull request later, if it is too
much of hustle for now.)

2020-08-17 22:28 UTC, dcallega commented
Thank you so much for the feedback! I did my best and I think I fixed this.
Does the message make more sense now?

2020-08-17 22:46 UTC, iburago commented
LGTM.

I assume, we leave adding the dissertation for later?

2020-08-17 22:52 UTC, igorburago approved these changes

2020-08-17 22:56 UTC, iburago commented
Oh, I just realized that we had also forgotten to add an entry for
this newly acquired degree in the education section. Could you
please add the following after line 16?

```
- degree: Ph.D. in Computer Science
  institution: University of California, Irvine, U.S.
  year: 2020
```

2020-08-17 22:57 UTC, igorburago requested changes
Oh, I just realized that we have forgotten to add an entry for this
newly acquired degree in the education section. Could you please
add the following after line 16?

```
- degree: Ph.D. in Computer Science
  institution: University of California, Irvine, U.S.
  year: 2020
```

2020-08-17 23:06 UTC, dcallega commented
I did not add it because I did not get the information from Delaram about her thesis' title.
However it makes sense to add the degree as is and update that later.

2020-08-17 23:21 UTC, iburago commented
> I did not add it because I did not get the information from Delaram
> about her thesis' title.

That’s fine.

> However it makes sense to add the degree as is and update that later.

Of course. (In fact, it would perhaps be great to do that for all alumni.)

2020-08-17 23:22 UTC, iburago commented
LGTM.

2020-08-17 23:22 UTC, igorburago approved these changes

2020-08-17 23:23 UTC, merged