feature: Add code link to bibtex entry
uci-iasl/website pull request #33
Opened 2020-08-14 22:09 UTC by dcallega

Adding a change to read the 'code' field in a bibtex entry, and rediect the click to the repository specified in the bibtex entry field.

2020-08-15 05:06 UTC, igorburago requested changes

2020-08-15 05:06 UTC, igorburago commented on layouts/partials/bib/entry/extras.html
> +  <span class="{{ $class }} pubref"><a href="{{ . }}" target="_blank" rel="noopener">Code</a></span>
Change the `pubref` class to, say, `coderef`:

```suggestion
  <span class="{{ $class }} coderef"><a href="{{ . }}" target="_blank" rel="noopener">Code</a></span>
```

The classes of different extras’ `<span>`s (beyond the common
`$class`) are supposed to be different to allow for their potential
differentiation in styling.

2020-08-15 05:06 UTC, iburago commented on layouts/partials/bib/entry/extras.html
> +{{- end -}}
Move the whole `with`-block for the `.entry.code` before the one for
`.entry.doi`, i.e., move lines 17 through 19 to just above line 14.

I think it is better to keep the Release link the last one before the
Abstract and BibTeX buttons.

2020-08-15 05:10 UTC, iburago commented
Did you take an inspiration for the `code` name of the BibTeX field
to use from any of the existing BibTeX processors, or is it our own
custom name?

It is okay either way, and I’m in favor of the change in general, but,
in the latter case, I will need to spend a little bit of time researching
whether a similar extension practice already exists before merging
this variant: It is always better to adopt an existing customization,
unless there are none or there is a reason not to.

2020-08-17 22:49 UTC, dcallega commented
The idea here was to introduce a field unique to our project. As far as I know there is no "code" field in standard bibtex files.
I just tried to keep it clean, and I when I could not find any conflict, I used such keyword.

2020-08-17 22:51 UTC, dcallega commented
I applied the requested changes and squashed the commits on this feature in one.
I tried to apply the new knowledge, but being the first-ish thought out commit, it might still be suboptimal.
Feedback as always is greatly appreciated!
Once this is closed I will move to #34 .

2020-08-17 23:00 UTC, iburago commented
I think, the class name is still `pubref`. Could you please change it [as suggested](https://github.com/uci-iasl/website/pull/33/files#r470938490)?

2020-08-17 23:11 UTC, iburago commented
I would also recommend changing the commit subject like so:

> Support source code links in bibliography entries

I would say that `bibentry:` prefix is unnecessary here.
My logic of using the prefixes in commit messages is as follows:

- **No prefix:** Changes to the layout templates and styling of the
website, i.e., anything that Hugo uses to generate the pages, *except
for the content itself* (e.g., Markdown files, PDFs, bibliography data,
images, etc.).
- **Site section-based prefix:** Changes to the content of the site.
The prefix is either a section name alone—`updates`, `people`,
`projects`, `publications` (same as the names of subfolders in
the `content` directory)—or a section name followed by slash and
a subsection—e.g., `people/dcallega` or `projects/city-iot`—when
the commit pertains only the files of that subsection. For changes
in bibliography data, I use a pseudo-section name `bib`.
- **File path-based prefix:** Changes to any site-related external
tools, not used directly to build the website, such as documentation
(beyond the README file), scripts, etc., e.g., `scripts/bibtex2yaml`
or `scripts/gethugo`.

2020-08-17 23:18 UTC, iburago commented
> As far as I know there is no "code" field in standard bibtex files.

That is correct. The reason I asked is that, for some extensions,
many modern BibTeX processors, such as BibLaTeX, for instance,
already employ some non-standard fields extending BibTeX for
some applications. For example, to link to digital preprints, BibLaTeX
uses the `eprint`, `eprinttype`, and `eprintclass` fields.

I am not aware of any existing BibTeX extension field being used
for linking to source code, either, so, I think, we will go with `code`.
But I will take another quick look first.

2020-08-17 23:19 UTC, dcallega commented
Please let me know if further edits are required.
I squashed the new edits, integrating them into the original commit (edited).

2020-08-17 23:23 UTC, dcallega commented
> It looks like the class name is still `pubref`. Could you please change it [as suggested](https://github.com/uci-iasl/website/pull/33/files#r470938490)?

Ops. Done

2020-08-17 23:29 UTC, dcallega commented
> I would also recommend changing the commit subject like so:
> 
> > Support source code links in bibliography entries
> 
> I would say that `bibentry:` prefix is unnecessary here.
> My logic of using the prefixes in commit messages in this repository
> is as follows:
> 
> * **No prefix:** Changes to the layout templates and styling of the
>   website, i.e., anything that Hugo uses to generate the pages, _except
>   for the content itself_ (e.g., Markdown files, PDFs, bibliography data,
>   images, etc.).
> * **Site section-based prefix:** Changes to the content of the site.
>   The prefix is either a section name alone—`updates`, `people`,
>   `projects`, `publications` (same as the names of subfolders in
>   the `content` directory)—or a section name followed by slash and
>   a subsection—e.g., `people/dcallega` or `projects/city-iot`—when
>   the commit pertains only the files of that subsection. For changes
>   in bibliography data, I use a pseudo-section name `bib`.
> * **File path-based prefix:** Changes to any site-related external
>   tools, not used directly to build the website, such as documentation
>   (beyond the README file), scripts, etc., e.g., `scripts/bibtex2yaml`
>   or `scripts/gethugo`.

Ok, now I see the pattern! Sorry I probably didn't read enough of them to see it.
Do we want to copy/paste this to the README or even create a small section for "Contribution style"?
I really like this, but I would not be able to explain it myself and we need to do so as we distribute the load to others.

2020-08-17 23:34 UTC, iburago commented
Could you please expand the term `bibentry` in the commit message
to `bibliography entries` or something similar? It is not an established
term in the repository lingo, and unless we want to establish it as one,
it is better not to use it as such.

It makes it easier for people to understand and contribute later, when
there is less ad-hoc abbreviations and unidiomatic terms being used
in commit history. I learned that it is a good rule in general from seeing
how things are done in the repositories of bigger collaborative projects.

2020-08-18 00:03 UTC, iburago commented
Okay, I adjusted the commit message myself.

I also excluded the `code` field from being included into
the generated BibTeX snippets as a non-standard one.

2020-08-18 00:04 UTC, igorburago approved these changes

2020-08-18 00:05 UTC, igorburago approved these changes

2020-08-18 00:05 UTC, merged